tunnel: ${TUNNEL_TOKEN}
credentials-file: /etc/cloudflared/${TUNNEL_TOKEN}.json

ingress:
  - hostname: omni.nexuslbs.org
    service: http://dashboard:3001
  - hostname: omni-grafana.nexuslbs.org
    service: http://grafana:3000
  - service: http_status:404
