channels:
  mattermost-mg5cjsh5:
    platform: mattermost
    resource_identifier: mg5cjsh5ujyxtd5nk7b5d5yx1e
    profile: omni
    model: test-tool-caller
    provider: noop
    closed: false
  mattermost-setup:
    platform: mattermost
    resource_identifier: zswtrbugn7b8mcbtarcwe6isfh
    profile: omni
    closed: false
  mm-kanban:
    platform: mattermost
    resource_identifier: wkbugy5xcff1teeqgnty5ck4io
    profile: omni
    model: deepseek-v4-flash
    provider: deepseek
    closed: false
  mattermost-d6bmh64b:
    platform: mattermost
    resource_identifier: d6bmh64bk7foukhw31ga4rhm3a
    profile: omni
  cron:
    resource_identifier: cron
    profile: omni
  g30-b:
    resource_identifier: g30-b
    profile: omni
  kanban:
    resource_identifier: kanban
    profile: omni
  mattermost-stable-channel:
    platform: mattermost
    resource_identifier: 7p9ozmn7pjbb8erza75udctwcw
    profile: omni
    model: deepseek-v4-flash
    provider: deepseek
    closed: false
  mattermost-af66ardb:
    platform: mattermost
    resource_identifier: af66ardbd3dffe7gwxnokzi19c
    profile: omni
  g30-a:
    resource_identifier: g30-a
    profile: omni
