tools:
  test-rust-tool:
    url: https://github.com/nexuslbs/omni-plugins.git
    path: tools/test-rust-tool
providers:
  noop:
    url: https://github.com/nexuslbs/omni-plugins.git
    path: providers/noop-full
